-- ============================================================
-- authz0182-insert-returning-seam.sql — an INSERT that asks for the row back
-- must be able to READ the row it just wrote.
--
-- THE SEAM THIS COVERS, AND WHY IT WAS EMPTY. 0181: `project_files_read` called
-- `prof_can_see_file(id)`, which answered by SELECTing `project_files` for that
-- id. PostgREST issues `RETURNING *` for `Prefer: return=representation`, the
-- row is not visible to that lookup yet, the SELECT policy fails, and Postgres
-- rejects the whole statement — while the INSERT itself was allowed. Google
-- Drive is written BEFORE the row, so each refusal left a publicly-shared PDF
-- that nothing referenced. Three signed หนังสือโครงการ were lost that way and
-- the fault hid for six days.
--
-- HANDOFF §13c: "No test in this repo exercises a PostgREST write the way the
-- browser makes it. Every 0181 assertion is either a live SQL proof or a
-- source-shape check; the seam between them — `Prefer: return=representation` —
-- is exactly where the bug lived, and nothing covers it." This is that test.
-- **24 INSERT call sites across 23 tables ask for the row back**, so this is a
-- shape with 23 places to recur, not a one-table accident. Measured 2026-09-10;
-- re-derive it rather than trusting this number, because it will drift:
--
--   grep -rn "return=representation" src/js/ passport/js/ | wc -l   # 131 lines
--   # …then keep the dbRest() calls whose options say method:'POST'.
--
-- §30 below needs no such list: it sweeps EVERY SELECT policy in `public`, so a
-- 24th table is covered the moment it has a policy, with nothing to update here.
-- A guard written from a list can only ever be as right as the list.
--
-- IT HAS THREE PARTS, AND THE THIRD IS WHAT MAKES THE SECOND TRUSTWORTHY.
--   §A  THE MECHANISM, live. A synthetic table with a self-looking-up SELECT
--       policy: a bare INSERT is ALLOWED and the same INSERT ... RETURNING is
--       REFUSED, by the same principal, in the same transaction. Then the policy
--       is rewritten against the NEW ROW'S OWN COLUMNS and RETURNING starts
--       working. That is 0181 and its fix, reproduced from nothing in ~20 lines,
--       so the pattern this proof hunts is demonstrated to cause the failure
--       rather than asserted to.
--   §B  THE DETECTOR, over every real SELECT policy in `public`. For each one it
--       takes the functions the policy ACTUALLY depends on — from `pg_depend`,
--       which records the exact OID, so an overload cannot be confused — and
--       flags any whose body reads the policy's own table.
--   §C  THE DETECTOR'S OWN CONTROL, both directions. It must FLAG §A's
--       deliberately bad policy (or a green §B means only that it is blind) and
--       must NOT flag the healthy two-argument `prof_can_see_file`.
--
-- ⚠️ WHY `pg_depend` AND NOT A REGEX ON THE PREDICATE. The first draft matched
-- function names in `pg_policies.qual` and joined to `pg_proc` on `proname`. It
-- reported `project_files_read` as a live self-lookup — a FALSE POSITIVE: the
-- policy calls `prof_can_see_file(id, sign_request_id)` (the fix, whose body
-- touches only `project_sign_requests`), and the regex had matched the body of
-- the one-argument overload that 0181 kept as a thin wrapper for other callers.
-- A guard that fires on the healthy case is worse than no guard, and the name of
-- a Postgres function is not its identity. `pg_depend` gives the identity.
--
-- ⚠️ SCOPE, stated rather than implied: §B follows ONE level — the functions a
-- policy depends on directly. A self-lookup buried in a function called BY one
-- of those is not detected, because these functions have string bodies and
-- Postgres records no dependency for what they call. 0181 lived at level one.
--
--   node tools/db-query.mjs tools/authz0182-insert-returning-seam.sql
-- ============================================================
begin;

create temporary table probe (step text, expected text, got text) on commit drop;

-- ── §A the mechanism, built from nothing ────────────────────────────────────
create table public._seam_probe (
  id    bigint generated by default as identity primary key,
  owner uuid,
  note  text
);
alter table public._seam_probe enable row level security;
grant select, insert on public._seam_probe to authenticated;

-- The BAD read rule: it identifies the row by looking it up in its own table.
-- This is `prof_can_see_file(id)` with the names changed.
create function public._seam_can_see(p_id bigint) returns boolean
  language sql stable security definer set search_path to public as $fn$
  select exists (select 1 from public._seam_probe t where t.id = p_id)
$fn$;

create policy seam_insert on public._seam_probe
  for insert to authenticated with check (true);
create policy seam_read_bad on public._seam_probe
  for select to authenticated using (public._seam_can_see(id));

-- One instrument, three possible answers. A refused RETURNING raises; a refused
-- row-match returns zero rows; a missing GRANT raises differently. Scoring them
-- alike is how a broken service reads as a working guard.
create or replace function pg_temp.as_user(p_sql text) returns text as $$
declare n int; msg text;
begin
  begin
    perform set_config('request.jwt.claims',
      json_build_object('sub','11111111-1111-4111-8111-111111111111',
                        'role','authenticated')::text, true);
    execute 'set local role authenticated';
    execute p_sql;
    get diagnostics n = row_count;
    raise exception using errcode = '22000',
      message = 'UNDO:' || case when n > 0 then 'allow' else 'deny-rls' end;
  exception
    when sqlstate '22000' then
      get stacked diagnostics msg = message_text;
      execute 'reset role';
      return replace(msg, 'UNDO:', '');
    when others then
      get stacked diagnostics msg = message_text;
      execute 'reset role';
      return case
        when msg like '%permission denied%'  then 'deny-grant'
        when msg like '%violates row-level%' then 'deny-check'
        else 'ERROR ' || left(msg, 40) end;
  end;
end $$ language plpgsql;

-- The two halves of 0181, side by side, same principal, same statement but for
-- the RETURNING. If these two ever agree, the bug cannot happen and this proof
-- has stopped testing anything.
insert into probe select '10. bare INSERT is allowed', 'allow',
  pg_temp.as_user($q$insert into public._seam_probe (note) values ('a')$q$);
insert into probe select '11. the SAME INSERT ... RETURNING * is refused', 'deny-check',
  pg_temp.as_user($q$insert into public._seam_probe (note) values ('b') returning *$q$);

-- ⚠️ `returning 1` reads no column, so Postgres never applies the SELECT policy
-- and the case passes while the feature is broken. PostgREST issues `RETURNING *`.
-- This assertion is here so nobody "simplifies" §11 into the form that lies.
insert into probe select '12. …but RETURNING 1 passes — the form that LIES', 'allow',
  pg_temp.as_user($q$insert into public._seam_probe (note) values ('c') returning 1$q$);

-- Now the 0181 fix: judge the row by ITS OWN COLUMNS, which exist during RETURNING.
drop policy seam_read_bad on public._seam_probe;
create policy seam_read_good on public._seam_probe
  for select to authenticated using (owner = auth.uid());

insert into probe select '13. rewritten against the NEW ROW: RETURNING * works', 'allow',
  pg_temp.as_user($q$insert into public._seam_probe (owner, note)
                     values (auth.uid(), 'd') returning *$q$);
insert into probe select '14. and it is still a SCOPE, not using(true)', 'deny-check',
  pg_temp.as_user($q$insert into public._seam_probe (owner, note)
                     values ('22222222-2222-4222-8222-222222222222', 'e') returning *$q$);

-- ── §A2 a standing subject for the detector ─────────────────────────────────
-- ⚠️ THIS TABLE EXISTS BECAUSE THE CONTROL CAUGHT A BUG IN THIS PROOF. The
-- first draft asked the detector to find `seam_read_bad` — which §A had already
-- DROPPED in order to install the good policy. §20 duly reported the detector
-- blind. The detector was fine; the proof had removed its subject before
-- looking. A control that only ever confirms good news would have said nothing.
-- So the bad shape now lives on its own table that nothing rewrites.
create table public._seam_detect (id bigint generated by default as identity primary key);
alter table public._seam_detect enable row level security;
create function public._seam_detect_can_see(p_id bigint) returns boolean
  language sql stable security definer set search_path to public as $fn$
  select exists (select 1 from public._seam_detect t where t.id = p_id)
$fn$;
create policy seam_detect_read_bad on public._seam_detect
  for select to authenticated using (public._seam_detect_can_see(id));

-- ── §B the detector, over every SELECT policy in public ─────────────────────
-- pg_depend gives the EXACT function a policy calls, overloads included.
create temporary view seam_findings as
select cl.relname as tbl, pol.polname as pol, p.oid::regprocedure::text as fn
  from pg_depend d
  join pg_policy pol on pol.oid = d.objid and d.classid = 'pg_policy'::regclass
  join pg_class cl   on cl.oid = pol.polrelid
  join pg_namespace n on n.oid = cl.relnamespace
  join pg_proc p     on p.oid = d.refobjid and d.refclassid = 'pg_proc'::regclass
 where n.nspname = 'public'
   and pol.polcmd in ('r', '*')                 -- SELECT, or ALL
   and pg_get_functiondef(p.oid) ~* ('(from|join)\s+(public\.)?' || cl.relname || '\y');

-- ── §C the detector's control, BOTH directions ──────────────────────────────
-- Without this, a green §B means "no policy is broken" OR "the detector cannot
-- see a broken one", and those look identical on the page.
insert into probe select '20. detector FLAGS the deliberately bad policy', 'seam_detect_read_bad',
  coalesce((select string_agg(pol, ',') from seam_findings
             where tbl = '_seam_detect'), '(nothing — DETECTOR IS BLIND)');

insert into probe select '21. detector does NOT flag the healthy 2-arg form', '(none)',
  coalesce((select string_agg(pol||'/'||fn, ',') from seam_findings
             where tbl = 'project_files'), '(none)');

-- The healthy form must still be the one the policy actually calls — read from
-- pg_depend, not from the migration that wrote it.
insert into probe select '22. project_files_read calls the 2-ARG form', 'prof_can_see_file(bigint,text)',
  (select p.oid::regprocedure::text
     from pg_depend d
     join pg_policy pol on pol.oid = d.objid and d.classid = 'pg_policy'::regclass
     join pg_proc p on p.oid = d.refobjid and d.refclassid = 'pg_proc'::regclass
    where pol.polname = 'project_files_read' and p.proname = 'prof_can_see_file');

-- And the hazardous 1-arg wrapper, which 0181 KEPT for other callers, must not
-- be reachable from any policy. This is the assertion that would have caught
-- 0181 on the day it shipped.
insert into probe select '23. NO policy depends on the 1-arg wrapper', '(none)',
  coalesce((select string_agg(pol.polname, ',')
              from pg_depend d
              join pg_policy pol on pol.oid = d.objid and d.classid = 'pg_policy'::regclass
              join pg_proc p on p.oid = d.refobjid and d.refclassid = 'pg_proc'::regclass
             where p.oid::regprocedure::text = 'prof_can_see_file(bigint)'), '(none)');

-- ── §D the real finding: every OTHER table is clean ─────────────────────────
-- Reported as a NAME LIST, never a count: a count that changes tells you
-- nothing about which table it was, and the fastest way to green a count is to
-- edit the number.
insert into probe select '30. no REAL table has a self-lookup SELECT policy', '(none)',
  coalesce((select string_agg(distinct tbl||'.'||pol, ', ' order by tbl||'.'||pol)
              from seam_findings where tbl not in ('_seam_probe','_seam_detect')), '(none)');

-- The control for §30: it must have examined a realistic number of policies, or
-- "(none)" means "it looked at nothing". A sweep whose subject can be empty
-- reports a healthy tree and a broken query identically.
insert into probe select '31. …and it examined a real policy set (>40)', 'true',
  (select (count(*) > 40)::text from pg_policy pol
     join pg_class cl on cl.oid = pol.polrelid
     join pg_namespace n on n.oid = cl.relnamespace
    where n.nspname = 'public' and pol.polcmd in ('r','*'));

select step,
       case when got is not distinct from expected then 'PASS' else 'FAIL' end as result,
       expected, got
  from probe order by step;

rollback;
